# -*- coding: utf-8 -*-
"""KMeansClustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDwTVtDnHQJitkmgtPpVAmQxW0Pg53eQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

driver=pd.read_csv("driver-data.csv")
driver.head()

x1=driver['mean_dist_day'].values
x2=driver['mean_over_speed_perc'].values
X=np.array(list(zip(x1,x2)))

plt.xlabel('mean_dist_day')
plt.ylabel('mean_over_speed_perc')

plt.scatter(x1,x2,c='black',s=7)

from sklearn.cluster import KMeans
#number of clusters
k=4
kmeans=KMeans(n_clusters=k)
#fitting of data
kmeans.fit(X)
#Getting the cluster labels
labels=kmeans.predict(X)
#Cetroid values
centroid=kmeans.cluster_centers_
print(centroid)
x,y=[],[]
for i in range(k):
  x.append(centroid[i][0])
  y.append(centroid[i][1])

print(x,y)

plt.xlabel('mean_dist_day')
plt.ylabel('mean_over_speed_perc')

plt.scatter(x1,x2,c='#050505',s=7)
plt.scatter(x,y,marker='*',c='g',s=200)